language: ruby


# This intended to fix bundler bug in Ruby 1.9.3 (see https://github.com/travis-ci/travis-ci/issues/5239)
before_install:
  - gem install bundler


rvm:
- 2.0.0
- 1.9.3
- jruby-19mode

script: "bundle exec rspec spec"
